version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: sentinel_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sentinel

    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql



  neo4j:
    image: neo4j:4.4
    container_name: sentinel_neo4j
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt protocol
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  neo4j_data:
